projects/wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"

urlpatterns = [  # type: ignore
    path("", views.index, name="index"),
    path("wiki/<title>", views.entry, name="entry"),
    path("search", views.search, name="search"),  # type: ignore
    path("random", views.random_page, name="random"),
    path("create", views.create, name="create"),
    path("edit/<title>", views.edit, name="edit"),
]

projects/wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

projects/wiki/encyclopedia/models.py
# from django.db import models

# Create your models here.

projects/wiki/encyclopedia/views.py
from random import randint

from django.http import HttpRequest
from django.shortcuts import redirect, render
from markdown2 import markdown  # type: ignore

from . import util


def index(request: HttpRequest):
    return render(request, "encyclopedia/index.html", {"entries": util.list_entries()})


def entry(request: HttpRequest, title: str):
    content = util.get_entry(title.strip())

    if content is None:
        content = "## Page was not found!"

    content = markdown(content)  # type: ignore

    return render(
        request, "encyclopedia/entry.html", {"content": content, "title": title}
    )


def search(request: HttpRequest):
    query = request.GET.get("search_query")

    if query is not None:
        query = query.strip()

        if query in util.list_entries():
            return redirect("encyclopedia:entry", title=query)
        return render(
            request,
            "encyclopedia/search.html",
            {"entries": util.search(query), "search_query": query},
        )

    return query


def edit(request: HttpRequest, title: str):
    content = util.get_entry(title.strip())

    if content is None:
        return render(request, "encyclopedia/edit.html", {"error": "404 Not Found"})

    if request.method == "POST":
        content = request.POST.get("content")

        if content is not None:
            content = content.strip()
        if not content:
            return render(
                request,
                "encyclopedia/edit.html",
                {
                    "message": "Cannot save with an empty field.",
                    "title": title,
                    "content": content,
                },
            )

        util.save_entry(title, content)

        return redirect("encyclopedia:entry", title=title)

    return render(
        request, "encyclopedia/edit.html", {"content": content, "title": title}
    )


def create(request: HttpRequest):
    if request.method == "POST":
        title = request.POST.get("title")

        if title is not None:
            title.strip()

        content = request.POST.get("content")

        if content is not None:
            content.strip()

        if not title or not content:
            return render(
                request,
                "encyclopedia/add.html",
                {
                    "message": "Cannot save with an empty field.",
                    "title": title,
                    "content": content,
                },
            )

        if title in util.list_entries():
            return render(
                request,
                "encyclopedia/add.html",
                {
                    "message": "This title already exists. Try another one!",
                    "title": title,
                    "content": content,
                },
            )

        util.save_entry(title, content)

        return redirect("encyclopedia:entry", title=title)

    return render(request, "encyclopedia/add.html")


def random_page(_request: HttpRequest):
    entries = util.list_entries()

    random_title = entries[randint(0, len(entries) - 1)]

    return redirect("encyclopedia:entry", title=random_title)

projects/wiki/encyclopedia/templates/encyclopedia/add.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Create
{% endblock %}

{% block body %}
<h1>
  Create A New Page
</h1>

<div class="container">
  {% if message %}
  <div class="alert alert-danger" role="alert">
    {{ message }}
  </div>
  {% endif %}

  <form method="POST">
    {% csrf_token %}
    <div class="form">
      <div class="my-3">
        <label for="title">
          Title
        </label>

        <input type="text" id="title" class="form-control" name="title" placeholder="Title Of The Page" {%if title%}
          value="{{ title }}" {%endif%} />
      </div>

      <div>
        <label for="content">
          Content
        </label>

        <textarea class="form-control" id="content" cols="30" name="content" rows="10">
          {% if content %}
          {{ content }}
          {% endif %}
        </textarea>
      </div>

      <input type="submit" value="Save Page" class="btn btn-success my-3" />
    </div>
  </form>

</div>

{% endblock %}

projects/wiki/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Edit
{% endblock %}

{% block body %}

<h1>
  Editing Page: {{ title }}
</h1>

<div class="container">
  {% if error %}
  <h2 align="center">
    404 Not Found
  </h2>
  {% else %}

  {% if message %}
  <div class="alert alert-danger" role="alert">
    {{ message }}
  </div>

  {% endif %}

  <form method="POST">
    {% csrf_token %}

    <div class="form mt-3">
      <div>
        <label for="content">
          Content
        </label>

        <textarea class="form-control" id="content" cols="30" name="content" rows="10">
          {% if content %}
          {{ content }}
          {% endif %}
        </textarea>
      </div>

      <input type="submit" value="Save" class="btn btn-success my-3" />
    </div>
  </form>

  {% endif %}
</div>

{% endblock %}

projects/wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}


{% block title %}
{{ title }}
{% endblock %}

{% block body %}

<a href="{% url 'encyclopedia:edit' title %}" class="badge badge-info">
  Edit This Page
</a>

{{ content | safe }}

{% endblock %}

projects/wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Encyclopedia
{% endblock %}

{% block body %}
<h1>
  Table of Contents
</h1>
<hr>
<ul>
  {% for entry in entries %}

  <a href="{% url 'encyclopedia:entry' entry %}">
    <li>
      {{ entry }}
    </li>
  </a>

  {% endfor %}
</ul>

{% endblock %}

projects/wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en-US">

  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'encyclopedia/layout.css' %}">

    <title>
      {% block title %}
      {% endblock %}
    </title>
  </head>

  <body>
    <div class="row">
      <div class="sidebar col-lg-2 col-md-3">

        <h2>
          Wikipedia
        </h2>

        <br>

        <form action="{% url 'encyclopedia:search' %}">
          {% csrf_token %}
          <input class="search" type="text" name="search_query" placeholder="Search Encyclopedia" required>
        </form>

        <br>

        <div>
          <a href="{% url 'encyclopedia:index' %}">
            Home
          </a>
        </div>

        <div>
          <a href="{% url 'encyclopedia:create' %}">
            New Page
          </a>
        </div>

        <div>
          <a href="{% url 'encyclopedia:random' %}">
            Random Page
          </a>
        </div>

        {% block nav %}
        {% endblock %}
      </div>

      <div class="main col-lg-10 col-md-9">
        {% block body %}
        {% endblock %}
      </div>
    </div>
  </body>

</html>

projects/wiki/encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Search
{% endblock %}

{% block body %}
<h1>
  Related Pages
</h1>

<p>
  Search Results Found With:
  <b>
    {{ search_query }}
  </b>
</p>

<ul>
  {% for entry in entries %}

  <a href="{% url 'encyclopedia:entry' entry %}">
    <li>
      {{ entry }}
    </li>
  </a>

  {% endfor %}
</ul>

{% endblock %}