projects/project4/network/urls.py
from django.urls import path

from . import views

app_name = "network"

urlpatterns = [
    path("", views.index, name="index"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("register/", views.register, name="register"),
    path("post/", view=views.create_post, name="create_post"),
    path("like/<int:post_id>/", views.like, name="like"),
    path("update_post/<int:post_id>/", views.update_post, name="update_post"),
    path("profile/<str:username>/", views.profile, name="profile"),
    path("follow/<str:username>/", views.follow, name="follow"),
    path("following/", views.following, name="following"),
]

projects/project4/project4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("network.urls")),
]

projects/project4/network/models.py
from typing import Any, Dict
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.dispatch import receiver
from django.db.models.signals import post_save


class User(AbstractUser):
    id = models.AutoField(primary_key=True)


class Post(models.Model):
    id = models.AutoField(primary_key=True)

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="posts")

    content = models.CharField(max_length=500)

    posted_at = models.DateTimeField(auto_now_add=True)

    likes = models.ManyToManyField(User, default=0, related_name="liked_posts")  # type: ignore

    objects = models.Manager()


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    followers = models.ManyToManyField(User, default=0, related_name="follower_user")  # type: ignore

    following = models.ManyToManyField(User, default=0, related_name="following_user")  # type: ignore


@receiver(post_save, sender=User)
def create_profile(
    sender: type, instance: User, created: bool, **_kwargs: Dict[str, Any]
):
    if created:
        Profile.objects.create(user=instance)

projects/project4/network/forms.py
from django import forms

from .models import Post


class CreatePostForm(forms.ModelForm):
    content = forms.CharField(
        label="New Post",
        max_length=500,
        required=True,
        widget=forms.Textarea(
            attrs={
                "placeholder": "What is on your mind right now?",
                "autofocus": "autofocus",
                "class": "form-control",
                "rows": "3",
            }
        ),
    )

    class Meta:
        model = Post
        fields = ["content"]

projects/project4/network/views.py
import json

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods
from django.core.paginator import Page, Paginator
from django.core.serializers import serialize
from django.db import IntegrityError
from django.http import HttpRequest, HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt

from .forms import CreatePostForm
from .models import Post, Profile, User


def pagination(request: HttpRequest):
    all_posts = Post.objects.all().order_by("-posted_at")

    paginator = Paginator(all_posts, 10)

    page_number = request.GET.get("page")

    posts_per_page: Page = paginator.get_page(page_number)

    return posts_per_page


@csrf_exempt
def index(request: HttpRequest):
    posts_per_page = pagination(request)

    return render(
        request,
        "network/index.html",
        {
            "request": request,
            "create_post_form": CreatePostForm(),
            "posts": posts_per_page,
        },
    )


@csrf_exempt
@login_required
def following(request: HttpRequest):
    followed_users = request.user.profile.following.all()  # type: ignore

    followed_users_posts = Post.objects.filter(user__in=followed_users).order_by(
        "-posted_at"
    )

    return render(request, "network/following.html", {"posts": followed_users_posts})


def profile(request: HttpRequest, username: str):
    if request.method != "GET":
        return JsonResponse({"error": "This endpoint only accepts GET."}, status=400)

    try:
        user = get_object_or_404(User, username=username)
        profile = get_object_or_404(Profile, user=user)
    except User.DoesNotExist:
        return JsonResponse({"error": "User not found."}, status=404)
    except Profile.DoesNotExist:
        return JsonResponse({"error": "Profile not found."}, status=404)

    posts = Post.objects.filter(user=user).order_by("-posted_at")

    is_following = False

    if request.user.is_authenticated:
        is_following = profile.followers.filter(id=request.user.id).exists()  # type: ignore

    JsonResponse(
        {
            "message": f"You have gotten {user.username}'s profile.",
        },
        status=200,
    )

    return render(
        request,
        "network/profile.html",
        {
            "user": user,
            "profile": profile,
            "posts": posts,
            "is_following": is_following,
        },
    )


@csrf_exempt
@login_required
@require_http_methods(["POST", "DELETE"])
def follow(request: HttpRequest, username: str):
    profile = get_object_or_404(Profile, user__username=username)
    request_user_profile = get_object_or_404(Profile, user__username=request.user.username)  # type: ignore

    status_code = 201

    if request.method == "POST":
        request_user_profile.following.add(request.user)  # type: ignore
        profile.followers.add(request.user)  # type: ignore
    elif request.method == "DELETE":
        request_user_profile.following.remove(request.user)  # type: ignore
        profile.followers.remove(request.user)  # type: ignore
        status_code = 202

    return JsonResponse({"profile": serialize("json", [profile])}, status=status_code)


@csrf_exempt
@login_required
def create_post(request: HttpRequest):

    if request.method != "POST":
        return JsonResponse({"error": "This endpoint only accepts POST."}, status=400)

    data = json.loads(request.body)

    content = data.get("content")

    post = Post(user=request.user, content=content)

    post.save()

    return JsonResponse({"message": "The post has been made."}, status=201)


@csrf_exempt
@login_required
def update_post(request: HttpRequest, post_id: int):
    if request.method != "PUT":
        return JsonResponse({"error": "This endpoint only accepts PUT."}, status=400)

    data = json.loads(request.body)

    new_content = data.get("content")

    post = get_object_or_404(Post, pk=post_id)

    post.content = new_content

    post.save()

    return JsonResponse(
        {"message": "The post has been updated.", "new_content": new_content},
        status=201,
    )


@csrf_exempt
@login_required
def like(request: HttpRequest, post_id: int):
    if request.method != "POST":
        return JsonResponse({"error": "This endpoint only accepts POST."}, status=400)

    post = get_object_or_404(Post, id=post_id)
    user = request.user

    if user in post.likes.all():  # type: ignore
        post.likes.remove(user)  # type: ignore
    else:
        post.likes.add(user)  # type: ignore

    like_count = post.likes.count()  # type: ignore

    return JsonResponse(
        {"message": "Successful execution.", "likes": like_count},
        status=201,
    )


def login_view(request: HttpRequest):
    if request.method == "POST":

        username = request.POST.get("username")

        password = request.POST.get("password")

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)

            return HttpResponseRedirect(reverse("network:index"))
        else:
            return render(
                request,
                "network/login.html",
                {"message": "You have given an invalid username and/or password."},
            )
    else:
        return render(request, "network/login.html")


@login_required
def logout_view(request: HttpRequest):
    logout(request)

    return HttpResponseRedirect(reverse("network:index"))


def register(request: HttpRequest):
    if request.method == "POST":
        username = request.POST.get("username")

        email = request.POST.get("email")

        password = request.POST.get("password")

        confirmation = request.POST.get("confirmation")

        if password != confirmation:
            return render(
                request,
                "network/register.html",
                {"message": "Both passwords must match."},
            )

        try:
            user = User.objects.create_user(username, email, password)  # type: ignore

            user.save()  # type: ignore
        except IntegrityError:
            return render(
                request,
                "network/register.html",
                {"message": "This username has already been taken."},
            )

        login(request, user)  # type: ignore

        return HttpResponseRedirect(reverse("network:index"))
    else:
        return render(request, "network/register.html")

projects/project4/network/templates/network/following.html
{% extends "network/layout.html" %}

{% block title %}
Followings
{% endblock %}

{% block body %}

<div class="all-posts">
  {% for post in posts %}

  <div class="card all-posts mb-4 shadow">
    <div class="card-body">
      <h5 class="card-title">
        <strong>
          <a href="{% url 'network:profile' post.user %}">
            {{ post.user }}
          </a>
        </strong>
      </h5>

      <div id="post-content" class="mb-2">
        {{ post.content }}
      </div>

      <div class="mb-2">
        <button id="like" data-post-id="{{ post.id }}" type="button">
          &#x2665;&#xfe0f; {{ post.likes.count }}
        </button>
      </div>

      <div class="timestamp">
        {{ post.posted_at }}
      </div>
    </div>
  </div>

  <br>

  {% empty %}

  <p>
    <strong>
      No posts are available.
    </strong>
  </p>

  {% endfor %}
</div>

<hr>

<nav>
  <ul class="box pagination d-flex">
    {% if posts.has_previous %}

    <li class="page-item">
      <a class="page-link" href="?page={{ posts.previous_page_number }}">
        Previous
      </a>
    </li>

    {% endif %}

    {% if posts.has_next %}

    <li class="page-item">
      <a class="page-link" href="?page={{ posts.next_page_number }}">
        Next
      </a>
    </li>

    {% endif %}

  </ul>
</nav>

{% endblock %}

projects/project4/network/templates/network/index.html
{% extends "network/layout.html" %}

{% block body %}
{% endblock %}

projects/project4/network/templates/network/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en-US">

  <head>
    <meta charset="UTF-8" />

    <meta name="description" content="This is the layout that will parent all of this application's pages." />

    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" />

    <link rel="stylesheet" href="{% static 'network/styles.css' %}" />

    <script src="{% static 'network/index.js' %}">
    </script>

    <title>
      {% block title %}
      Social Network
      {% endblock %}
    </title>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'network:index' %}">
        Network
      </a>

      <div>
        <ul class="navbar-nav mr-auto">
          {% if request.user.is_authenticated %}

          <li class="nav-item">
            <a class="nav-link" href="{% url 'network:profile' request.user.username %}">
              <strong>
                {{ request.user.username }}
              </strong>
            </a>
          </li>

          {% endif %}

          <li class="nav-item">
            <a class="nav-link" href="{% url 'network:index' %}">
              Home
            </a>
          </li>

          {% if request.user.is_authenticated %}

          <li class="nav-item">
            <a class="nav-link" href="{% url 'network:following' %}">
              Following
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'network:logout' %}">
              Log Out
            </a>
          </li>

          {% else %}

          <li class="nav-item">
            <a class="nav-link" href="{% url 'network:login' %}">
              Login
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'network:register' %}">
              Register
            </a>
          </li>
        </ul>

        {% endif %}
      </div>
    </nav>

    <div class="body">
      {% block body %}
      {% endblock %}
    </div>
  </body>

</html>

projects/project4/network/templates/network/login.html
{% extends "network/layout.html" %}

{% block body %}

<h2>
  Login
</h2>

{% if message %}

<div>
  {{ message }}
</div>

{% endif %}

<form action="{% url 'network:login' %}" method="post">
  {% csrf_token %}

  <div class="form-group">
    <input autofocus class="form-control" type="text" name="username" placeholder="Username">
  </div>

  <div class="form-group">
    <input class="form-control" type="password" name="password" placeholder="Password">
  </div>

  <input class="btn btn-primary" type="submit" value="Login">
</form>

If you don't have an account, then
<a href="{% url 'network:register' %}">
  register here.
</a>

{% endblock %}

projects/project4/network/templates/network/profile.html
{% extends "network/layout.html" %}

{% block title %}
{{ user.username }} | Network
{% endblock %}

{% block body %}
<div class="card">
  <div class="card-body">
    <h2>
      {{ user.username }}
    </h2>

    <p>
      <strong>
        Followers:
      </strong>
      {{ profile.followers.count }}
    </p>

    <p>
      <strong>
        Following:
      </strong>
      {{ profile.following.count }}
    </p>

    <p>
      <strong>
        Email:
      </strong>
      {{ user.email }}
    </p>
  </div>

  {% if request.user.is_authenticated and request.user != user %}

  <div class="follow-buttons">

    <button id="follow-unfollow" class="btn btn-secondary" data-username="{{ user.username }}"
      data-action="{% if is_following %}DELETE{% else %}POST{% endif %}" data-is_following="{{ is_following }}"
      type="button">
      {% if is_following %}
      Unfollow
      {% else %}
      Follow
      {% endif %}
    </button>

    <!-- {% if is_following %}

    <button class="btn btn-secondary" data-username="{{ user.username }}" data-action="DELETE" type="button">
      Unfollow
    </button>

    {% else %}

    <button class="btn btn-secondary" title="Follow" data-username="{{ user.username }}" data-action="POST"
      type="button">
      Follow
    </button>

    {% endif %} !-->

  </div>

  {% endif %}

  <br>
</div>

<div class="all-posts">
  <h2>
    {{ user.username }}'s Posts
  </h2>

  <br>

  {% for post in posts %}

  <div class="card all-posts mb-4 shadow">
    <div class="card-body">
      <h5 class="card-title">
        <strong>
          <a href="{% url 'network:profile' post.user %}">
            {{ post.user }}
          </a>
        </strong>
      </h5>

      <div id="post-content" class="mb-2">
        {{ post.content }}
      </div>

      {% if request.user == post.user %}

      <div class="mb-2">
        <button class="btn btn-info" id="edit-post" data-post-id="{{ post.id }}" type="button">
          Edit
        </button>
      </div>

      {% endif %}

      {% if request.user.is_authenticated %}

      <div class="mb-2">
        <button id="like" data-post-id="{{ post.id }}" type="button">
          &#x2665;&#xfe0f; {{ post.likes.count }}
        </button>
      </div>

      {% endif %}

      <div class="timestamp">
        {{ post.posted_at }}
      </div>
    </div>

    <div class="hidden" id="edit-post-form" data-post-id="{{ post.id }}">
      <textarea id="edit-post-content" placeholder="Please tell us what is on your mind right now." rows="5" cols="75">
      {{ post.content }}
      </textarea>

      <br>

      <button class="btn btn-primary" id="save-edit" type="button">
        Save
      </button>
    </div>
  </div>

  <br>

  {% empty %}

  <p>
    <strong>
      No posts have been made yet.
    </strong>
  </p>

  {% endfor %}
</div>

<hr>

<nav>
  <ul class="box pagination d-flex">
    {% if posts.has_previous %}

    <li class="page-item">
      <a class="page-link" href="?page={{ posts.previous_page_number }}">
        Previous
      </a>
    </li>

    {% endif %}

    {% if posts.has_next %}

    <li class="page-item">
      <a class="page-link" href="?page={{ posts.next_page_number }}">
        Next
      </a>
    </li>

    {% endif %}

  </ul>
</nav>
{% endblock %}

projects/project4/network/templates/network/register.html
{% extends "network/layout.html" %}

{% block body %}

<h2>
  Register
</h2>

{% if message %}

<div>
  {{ message }}
</div>

{% endif %}

<form action="{% url 'network:register' %}" method="post">
  {% csrf_token %}

  <div class="form-group">
    <input class="form-control" autofocus type="text" name="username" placeholder="Username">
  </div>

  <div class="form-group">
    <input class="form-control" type="email" name="email" placeholder="Email Address">
  </div>

  <div class="form-group">
    <input class="form-control" type="password" name="password" placeholder="Password">
  </div>

  <div class="form-group">
    <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
  </div>

  <input class="btn btn-primary" type="submit" value="Register">
</form>

If you already have an account,
<a href="{% url 'network:login' %}">
  login here.
</a>

{% endblock %}