projects/commerce/auctions/urls.py
from django.urls import path

from . import views

app_name = "auctions"

urlpatterns = [  # type: ignore
    path("", views.index, name="index"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("register/", views.register, name="register"),
    path("create/", views.create, name="create"),
    path("listing/<int:id>", views.listing, name="listing"),
    path("watchlist", views.watchlist, name="watchlist"),
    path("watch/<int:auction_id>", views.watch, name="watch"),
    path("unwatch/<int:auction_id>", views.unwatch, name="unwatch"),
    path("categories/", views.list_categories, name="categories"),
    path("category/<str:category>", views.category, name="category"),
    path("update-bid/<int:id>", views.update_bid, name="update_bid"),
    path("close-bid/<int:id>", views.close_bid, name="close_bid"),
    path("comments/<int:id>", views.comments, name="comments"),  # type: ignore
]

projects/commerce/commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

projects/commerce/auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

CATEGORIES = [
    ("A", "Automotive"),
    ("B", "Health & Beauty"),
    ("C", "Collectibles & Art"),
    ("E", "Electronics"),
    ("F", "Fashion"),
    ("H", "Home & Garden"),
    ("I", "Business & Industrial"),
    ("M", "Movies, Music, & Books"),
    ("O", "Others"),
    ("P", "Pet"),
    ("R", "Real Estate"),
    ("S", "Sporting Goods"),
    ("T", "Toys & Games"),
]


class User(AbstractUser):
    watchlist_counter = models.IntegerField(default=0, blank=True)
    watchlist = models.ManyToManyField(  # type: ignore
        "AuctionListing", related_name="watchlist", blank=True
    )

    pass


class AuctionListing(models.Model):
    id = models.AutoField(primary_key=True)

    user = models.ForeignKey(User, on_delete=models.CASCADE)

    title = models.CharField(max_length=150)

    description = models.CharField(max_length=1000)

    starting_bid = models.DecimalField(max_digits=12, decimal_places=2, blank=True)

    image_url = models.URLField(
        blank=True,
        default="https://cdn2.thecatapi.com/images/MTY3ODIyMQ.jpg",
    )

    category = models.CharField(max_length=1, blank=True, null=True, choices=CATEGORIES)

    posted_at = models.DateTimeField(auto_now_add=True)

    active = models.BooleanField(default=True)

    bid_counter = models.IntegerField(default=1)

    winner = models.CharField(max_length=1000, blank=True, null=True)

    def __str__(self):
        return f"[{self.id}] {self.title}: by {self.user.username} - {self.posted_at}"


class Bid(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    auction = models.ForeignKey(AuctionListing, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=15, decimal_places=2, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.amount} was bidded on {self.auction} by {self.user.username} for {self.auction.title} posted by {self.auction.user}."


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    auction = models.ForeignKey(AuctionListing, on_delete=models.CASCADE)
    text = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user} commented on {self.auction.title} by {self.auction.user}: {self.text}"

projects/commerce/auctions/forms.py
import re
from decimal import Decimal

from django import forms

from .models import CATEGORIES, AuctionListing


def parse(value: str):
    value = re.sub(r"\s+", "", value)

    value = value.replace("$", "")

    value = value.replace(",", "")

    return Decimal(value)


class CustomDecimalField(forms.DecimalField):
    def clean(self, value: str):
        parsed = parse(value)

        return super().clean(parsed)


class CreateListingForm(forms.ModelForm):
    title = forms.CharField(
        label="Listing Title",
        max_length=150,
        required=True,
        widget=forms.Textarea(
            attrs={
                "class": "form-control",
                "placeholder": "The listing title.",
            }
        ),
    )

    description = forms.CharField(
        label="Listing Description",
        max_length=1000,
        required=True,
        widget=forms.Textarea(
            attrs={
                "class": "form-control",
                "placeholder": "Give a detailed description about the listing.",
            }
        ),
    )

    starting_bid = CustomDecimalField(
        label="Starting Bid",
        required=True,
        widget=forms.Textarea(
            attrs={
                "class": "form-control",
                "placeholder": "Provide the starting bid for this listing (e.g. 23987.99, $1,456.90, or 1450).",
            }
        ),
        max_digits=12,
        decimal_places=2,
    )

    image_url = forms.URLField(
        label="Image URL",
        required=False,
        widget=forms.Textarea(
            attrs={
                "class": "form-control",
                "placeholder": "Optional (Recommended): Provide an image link of the producted being listed so potential buyers are able to see the item.",
            }
        ),
    )

    category = forms.ChoiceField(
        required=False,
        choices=CATEGORIES,
    )

    class Meta:
        model = AuctionListing
        fields = ["title", "description", "starting_bid", "image_url", "category"]


class CommentForm(forms.Form):
    text = forms.CharField(
        label="",
        required=True,
        widget=forms.Textarea(
            attrs={
                "class": "form-control-md lead form-group",
                "rows": "3",
                "cols": "100",
            }
        ),
    )

    def clean_comment(self):
        text = self.cleaned_data.get("text")
        if len(text) > 0:  # type: ignore
            return text
        return self.errors

projects/commerce/auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.forms import ValidationError
from django.http import HttpRequest, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt

from .forms import CommentForm, CreateListingForm
from .models import CATEGORIES, AuctionListing, Bid, Comment, User


def index(request: HttpRequest):
    return render(
        request,
        "auctions/index.html",
        {
            "listings": AuctionListing.objects.filter(active=True)
            .order_by("-posted_at")
            .values()
        },
    )


def list_categories(request: HttpRequest):
    return render(request, "auctions/categories.html", {"categories": CATEGORIES})


def category(request: HttpRequest, category: str):
    listings = AuctionListing.objects.filter(category=category)

    return render(
        request,
        "auctions/category.html",
        {"listings": listings, "category": category},
    )


@login_required
def create(request: HttpRequest):
    if request.method == "POST":
        form = CreateListingForm(request.POST)

        if form.is_valid():
            title = form.cleaned_data["title"]

            description = form.cleaned_data["description"]

            starting_bid = form.cleaned_data["starting_bid"]

            CATEGORIES_DICT = {
                "A": "Automotive",
                "B": "Health & Beauty",
                "C": "Collectibles & Art",
                "E": "Electronics",
                "F": "Fashion",
                "H": "Home & Garden",
                "I": "Business & Industrial",
                "M": "Movies, Music, & Books",
                "O": "Others",
                "P": "Pet",
                "R": "Real Estate",
                "S": "Sporting Goods",
                "T": "Toys & Games",
            }

            category = CATEGORIES_DICT.get(form.cleaned_data["category"])

            image_url = form.cleaned_data["image_url"]

            # Save a record.
            auction = AuctionListing(
                user=User.objects.get(pk=request.user.id),  # type: ignore
                title=title,
                description=description,
                starting_bid=starting_bid,
                category=category,
                image_url=image_url,
            )

            auction.save()

            bid = Bid(amount=starting_bid, user=request.user, auction=auction)
            bid.save()

            return HttpResponseRedirect(reverse("auctions:index"))
        else:
            # If a field input is invalid.
            return render(request, "auctions/create.html", {"form": form})

    return render(request, "auctions/create.html", {"form": CreateListingForm()})


def listing(request: HttpRequest, id: int):
    try:
        listing = AuctionListing.objects.get(pk=id)

        bid = get_object_or_404(Bid, auction=listing)

        comments = Comment.objects.filter(auction=listing)

        if request.user.is_authenticated:
            user = get_object_or_404(User, id=request.user.id)  # type: ignore

            auction = get_object_or_404(AuctionListing, id=id)

            is_in_watchlist = user.watchlist.filter(id=auction.id).exists()  # type: ignore

            if is_in_watchlist:
                on_watchlist = True
            else:
                on_watchlist = False
        else:
            on_watchlist = False

        return render(
            request,
            "auctions/listing.html",
            {
                "listing": listing,
                "on_watchlist": on_watchlist,
                "request": request,
                "bid": bid,
                "comments": comments,
                "comment_form": CommentForm(),
            },
        )
    except AuctionListing.DoesNotExist:
        return render(
            request,
            "auctions/listing.html",
            {
                "code": 404,
                "message": "That auction doesn't exist!",
            },
        )


@login_required(login_url="auctions/login.html")
def watchlist(request: HttpRequest):
    return render(
        request, "auctions/watchlist.html", {"watchlist": request.user.watchlist.all()}  # type: ignore
    )


@login_required(login_url="auctions/login.html")
def watch(request: HttpRequest, auction_id: int):
    auction = get_object_or_404(AuctionListing, id=auction_id)

    request.user.watchlist.add(auction)  # type: ignore

    request.user.watchlist_counter += 1  # type: ignore

    request.user.save()

    render(
        request, "auctions/watchlist.html", {"watchlist": request.user.watchlist.all()}  # type: ignore
    )

    return HttpResponseRedirect(reverse("auctions:watchlist"))


@login_required(login_url="auctions/login.html")
def unwatch(request: HttpRequest, auction_id: int):
    auction = get_object_or_404(AuctionListing, id=auction_id)

    request.user.watchlist.remove(auction)  # type: ignore

    request.user.watchlist_counter -= 1  # type: ignore

    render(
        request, "auctions/watchlist.html", {"watchlist": request.user.watchlist.all()}  # type: ignore
    )

    return HttpResponseRedirect(reverse("auctions:watchlist"))


@login_required(login_url="auctions/login.html")
def update_bid(request: HttpRequest, id: int):
    amount = request.POST["bid"]  # type: ignore

    if amount:
        amount = float(amount)  # type: ignore
        auction = get_object_or_404(AuctionListing, id=id)
        if amount > get_object_or_404(Bid, id=id).amount:
            bid = get_object_or_404(Bid, id=id)
            bid.user, bid.amount = request.user, amount  # type: ignore
            bid.save()
            auction.bid_counter += 1  # type: ignore
            auction.save()
            return HttpResponseRedirect(reverse("auctions:index"))
        else:
            raise ValidationError("Bid must be greater than current Bid value")
    else:
        raise ValidationError("Bid must be greater than current Bid value")


@login_required
def close_bid(request: HttpRequest, id: int):
    auction = get_object_or_404(AuctionListing, id=id)
    auction.active, auction.winner = False, request.user.username  # type: ignore
    auction.save()
    return HttpResponseRedirect(reverse("auctions:index"))


@login_required  # type: ignore
def comments(request: HttpRequest, id: int):
    anonymous = User.first_name
    if request.user is not anonymous:
        form = CommentForm(request.POST)
        if form.is_valid():
            f = form.cleaned_data
            comment = Comment(
                user=request.user, auction=get_object_or_404(AuctionListing, id=id), **f
            )
            comment.save()
            return HttpResponseRedirect(reverse("auctions:listing", kwargs={"id": id}))
    else:
        return render(
            request,
            "auctions/login.html",
            {"message": "Must be logged in to be able to comment!"},
        )


def login_view(request: HttpRequest):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]  # type: ignore

        password = request.POST["password"]  # type: ignore

        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(
                request,
                "auctions/login.html",
                {"message": "Invalid username and/or password."},
            )
    else:
        return render(request, "auctions/login.html")


def logout_view(request: HttpRequest):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


@csrf_exempt
def register(request: HttpRequest):
    if request.method == "POST":
        username = request.POST["username"]  # type: ignore
        email = request.POST["email"]  # type: ignore

        # Ensure password matches confirmation
        password = request.POST["password"]  # type: ignore
        confirmation = request.POST["confirmation"]  # type: ignore

        if password != confirmation:
            return render(
                request, "auctions/register.html", {"message": "Passwords must match."}
            )

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)  # type: ignore
            user.save()  # type: ignore
        except IntegrityError:
            return render(
                request,
                "auctions/register.html",
                {"message": "Username already taken."},
            )
        login(request, user)  # type: ignore
        return HttpResponseRedirect(reverse("auctions:index"))
    else:
        return render(request, "auctions/register.html")

projects/commerce/auctions/templates/auctions/categories.html
{% extends "auctions/layout.html" %}

{% block title %}

Categories

{% endblock %}

{% block body %}

<h1 class="listing-single">
  View Categories
</h1>

<hr>

<div class="listing-single">
  {% for code, name in categories %}

  <a href="{% url 'auctions:category' category=name %}">
    {{ name }}
  </a>

  <br>

  <br>
  {% endfor %}
</div>

{% endblock %}

projects/commerce/auctions/templates/auctions/create.html
{% extends "auctions/layout.html" %}

{% block body %}

<h1>
  Create Listing
</h1>

<hr>

<form action="{% url 'auctions:create' %}" method="post">
  {% csrf_token %}
  {{ form }}

  <br>

  <br>

  <input class="form-btn" type="submit" />
</form>

{% endblock %}

projects/commerce/auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block body %}

{% for listing in listings %}
<div class="card auction-item mb-4 shadow">
  <a href="{% url 'auctions:listing' listing.id %}">
    {% if listing.image_url %}

    <div class="card-image-wrapper">
      <img class="card-img-top listing-img" src="{{ listing.image_url }}" height=200 alt="{{ listing.title }} photo">
    </div>

    {% endif %}

    <div class="card-body">
      <h5 class="card-title">
        {{ listing.title }}
      </h5>

      <div class="mb-2">
        <strong>
          Description:
        </strong>

        {{ listing.description }}
      </div>

      <div class="mb-2">
        <strong>
          Price:
        </strong>

        {% load format_starting_bid %}

        ${{ listing.starting_bid|format_starting_bid }}
      </div>

      <div class="mb-2">
        <strong>
          Category:
        </strong>

        {{ listing.category }}
      </div>

      <div class="auction-list-date">
        {{ listing.posted_at }}
      </div>
    </div>
  </a>
</div>

{% empty %}

<div>
  <b>
    No auctions yet.
  </b>
</div>
{% endfor %}

{% endblock %}

projects/commerce/auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

    <head>
        <title>{% block title %}Auctions{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
            integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
    </head>

    <body>
        <h1>
            Auctions
        </h1>

        <br>

        <div>
            {% if user.is_authenticated %}

            Signed in as

            <strong>
                {{ user.username }}
            </strong>

            {% else %}

            <strong>
                Not signed in.
            </strong>

            {% endif %}
        </div>

        <br>

        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auctions:index' %}">
                    Active Listings
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'auctions:categories' %}">
                    Categories
                </a>
            </li>

            {% if user.is_authenticated %}

            <li class="nav-item">
                <a class="nav-link" href="{% url 'auctions:create' %}">
                    Create Listing
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'auctions:watchlist' %}">
                    Watchlist
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'auctions:logout' %}">
                    Log Out
                </a>
            </li>

            {% else %}

            <li class="nav-item">
                <a class="nav-link" href="{% url 'auctions:login' %}">
                    Log In
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'auctions:register' %}">
                    Register
                </a>
            </li>

            {% endif %}
        </ul>

        <hr>

        {% block body %}

        {% endblock %}
    </body>

</html>

projects/commerce/auctions/templates/auctions/listing.html
{% extends "auctions/layout.html" %}

{% block title %}

{{ listing.id }} - Listing

{% endblock %}

{% block body %}

{% if message %}

<b>
  {{ message }}
</b>

{% endif %}

{% if user.is_authenticated and listing.user != request.user %}

{% if listing.active %}
<form
  action="{% if on_watchlist %}{% url 'auctions:unwatch' auction_id=listing.id %}{% else %}{% url 'auctions:watch' auction_id=listing.id %}{% endif %}"
  method="post">
  {% csrf_token %}

  <input type="submit" class="btn btn-primary"
    value="{% if on_watchlist %}Remove from Watchlist{% else %}Add to Watchlist{% endif %}" />
</form>
{% endif %}

{% endif %}

<h1 class="listing-single">
  View Listing
</h1>

<hr>

{% if listing.winner is not None %}

{% if request.user == bid.user %}

<h2 class="display-2 pb-5 text-success">
  Highest bid, you are the winner!
</h2>

{% endif %}

{% endif %}

<div class="listing-single">

  {% if listing.image_url %}

  <div class="card-image-wrapper">
    <img class="card-img-top listing-img" src="{{ listing.image_url }}" height=200 alt="{{ listing.title }} photo">
  </div>

  {% endif %}

  <br>

  <br>

  <h5 class="card-title">
    {{ listing.title }} by
    <i>
      {{ listing.user }}
    </i>

    -

    <i>
      {{ listing.user.email }}
    </i>
  </h5>

  <br>

  {% if listing.winner is None %}

  <p>
    <b>
      Status:
    </b>

    <span class="text-success lead">
      <strong>
        Available
      </strong>
    </span>
  </p>

  {% else %}

  <p>
    <b>
      Status:
    </b>

    <span class="text-danger lead">
      <strong>
        Sold
      </strong>
    </span>
  </p>

  {% endif %}

  {% if request.user == bid.user %}

  {% if listing.winner is not None %}

  <h5 class="text-muted pt-3">
    {{ listing.bid_counter }} bids in total.

    <span class="lead">
      Congratulations, {{ bid.user }}! 🎊
    </span>
  </h5>

  {% else %}

  <h5 class="text-muted pt-3">
    {{ listing.bid_counter }} bids so far.

    <span class="lead">
      Your bid is the current highest bid.
    </span>
  </h5>

  {% endif %}

  {% else %}
  <h5 class="text-muted pt-3">
    {{ listing.bid_counter }} bids so far.
  </h5>

  {% endif %}

  <br>

  <div class="mb-2">
    <strong>
      Description:
    </strong>

    {{ listing.description }}
  </div>

  <br>

  <div class="mb-2">
    <strong>
      Price (Starting Bid):
    </strong>

    {% load format_starting_bid %}

    ${{ listing.starting_bid|format_starting_bid }}
  </div>

  <br>

  <div class="mb-2">
    <strong>
      Category:
    </strong>

    {{ listing.category }}
  </div>

  <br>

  <div class="auction-list-date">
    {{ listing.posted_at }}
  </div>
</div>

<div class="col-md-5 pl-4 mx-left-auto">
  {% if not listing.user == request.user %}

  <form action="{% url 'auctions:update_bid' bid.id %}" method="post">
    {% csrf_token %}

    <div class="input-group mb-3">
      {% if listing.winner is not None %}

      {% if bid.user == request.user %}

      <div class="input-group-prepend">
        <button disabled class="btn bg-success disabled text-light" type="submit">
          Winner
        </button>
      </div>

      <input disabled type="number" min="{{ bid.amount }}" step="0.01" max="99999999999.99" class="form-control"
        name="bid" placeholder="Your won with a bid of ${{ bid.amount }}">

      {% else %}

      <div class="input-group-prepend">
        <button disabled class="btn bg-danger disabled text-light" type="submit">
          Sold
        </button>
      </div>

      <input disabled type="number" min="{{ bid.amount }}" step="0.01" max="99999999999.99" class="form-control"
        name="bid" placeholder="Highest bid: ${{ bid.amount }}">

      {% endif %}

      {% else %}

      <div class="input-group-prepend">
        <button class="btn btn-outline-secondary bg-info text-light" type="submit">
          Bid Now!
        </button>

      </div>

      <input required type="number" min="{{ bid.amount }}" step="0.01" max="99999999999.99" class="form-control"
        name="bid" placeholder="Current Bid: ${{ bid.amount }}">

      {% endif %}

    </div>
  </form>

  {% else %}

  <form action="{% url 'auctions:close_bid' bid.id %}" method="post">
    {% csrf_token %}

    <div class="input-group mb-3">
      <div class="input-group-prepend">
        <button class="btn btn-outline-secondary bg-danger text-light" type="submit">
          Close Bid
        </button>
      </div>

      <input disabled type="text" class="form-control" placeholder="Last bid: {{ bid.user }} (${{ bid.amount }})">
    </div>
  </form>

  {% endif %}

  <h5 class="text-muted pt-3">Comments:</h5>
  <form action="{% url 'auctions:comments' listing.id %}" class="form-group" method="post">
    {% csrf_token %}

    {{ comment_form }}

    <input class="btn btn-lg btn-outline-secondary" type="submit" value="Add comment">
  </form>

  <hr>

</div>

{% for comment in comments %}

<div class="card mb-3">
  <div class="card-header">
    <p class="h5 text-muted">
      {{ comment.user }} -

      <span class="text-muted lead">
        {{ comment.created_at }}
      </span>
    </p>
  </div>

  <div class="card-body">
    <p class="card-text lead">
      {{ comment.text }}
    </p>
  </div>
</div>

{% empty %}

<p class="display-4 pb-5 ml-3">
  No comments for this auction yet.
</p>

{% endfor %}

</div>

{% endblock %}

projects/commerce/auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

<h2>Register</h2>

{% if message %}
<div>{{ message }}</div>
{% endif %}

<form action="{% url 'auctions:register' %}" method="post">
    {% csrf_token %}
    <div class="form-group">
        <input class="form-control" autofocus type="text" name="username" placeholder="Username">
    </div>
    <div class="form-group">
        <input class="form-control" type="email" name="email" placeholder="Email Address">
    </div>
    <div class="form-group">
        <input class="form-control" type="password" name="password" placeholder="Password">
    </div>
    <div class="form-group">
        <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
    </div>
    <input class="btn btn-primary" type="submit" value="Register">
</form>

Already have an account? <a href="{% url 'auctions:login' %}">Log In here.</a>

{% endblock %}

projects/commerce/auctions/templates/auctions/watchlist.html
{% extends "auctions/layout.html" %}

{% block body %}

<h2>
  Watchlist
</h2>

{% for item in watchlist %}
<div class="container pb-5 mt-n2 mt-md-n3">
  <div class="row">
    <div class="col-xl-9 col-md-8">
      <div class="d-sm-flex justify-content-between my-4 pb-4 border-bottom">
        <div class="media d-block d-sm-flex text-center text-sm-left">

          <a class="cart-item-thumb mx-auto mr-sm-4" href="{% url 'auctions:listing' item.id %}">
            <img src="{{ item.image_url }}" alt=" {{item.title}}">
          </a>

          <div class="media-body pt-1">
            <h3 class="product-card-title font-weight-semibold">
              <a href="{% url 'auctions:listing' item.id %}">
                {{ item.title }}
              </a>
            </h3>

            <div class="font-size-sm mb-1">
              <span class="text-muted mr-2">
                Description:
              </span>

              {{ item.description }}
            </div>

            <div class="font-size-sm mb-1">
              <span class="text-muted mr-2">
                Author:
              </span>

              {{ item.user }}
            </div>

            {% if item.category %}

            <div class="font-size-sm mb-1">
              <span class="text-muted mr-2">
                Category:
              </span>

              {{ item.category | title }}
            </div>
            {% else %}
            <div class="font-size-sm mb-1">
              <span class="text-muted mr-2">
                Category:
              </span>
              Not listed.
            </div>

            {% endif %}

            {% if item.starting_bid %}

            <div class="font-size-sm text-success mb-1">
              <span class="text-muted mr-2">
                Price (Starting Bid):
              </span>

              {% load format_starting_bid %}

              ${{ item.starting_bid|format_starting_bid }}
            </div>

            {% else %}

            <div class="font-size-sm text-danger mb-1">
              <span class="text-muted mr-2">
                Price:
              </span>

              Not specified
            </div>

            {% endif %}

            {% if item.winner == None %}

            <div class="font-size-lg text-primary mb-1">
              <span class="text-muted mr-2">
                Eligibility Status:
              </span>

              Available
            </div>

            {% else %}

            <div class="font-size-lg text-danger mb-1">
              <span class="text-muted mr-2">
                Eligibility Status:
              </span>

              Sold
            </div>

            {% endif %}

            <span class="text-muted">
              Created {{ item.posted_at }}
            </span>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% empty %}

<div>
  <b>
    Nothing in your watchlist.
  </b>
</div>

{% endfor %}

{% endblock %}